image: Visual Studio 2019
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y
  - nuget sources add -Name github -Source %nuget_github_feed% -UserName %nuget_github_user% -Password %nuget_github_pass%

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - nuget restore
  - dotnet restore

build:
  verbosity: minimal
  project: Cogito.Kademlia.sln

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.Kademlia

deploy:
  provider: NuGet
  server: $(nuget_github_feed)
  username: $(nuget_github_user)
  api_key: $(nuget_github_pass)
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/

